<!-- JS Here -->
<script src="{{ asset('assets/js/vendor/jquary-3.7.1.min.js') }}"></script>
<script src="{{ asset('assets/js/vendor/bootstrap-bundle.js') }}"></script>
<script src="{{ asset('assets/js/vendor/imagesloaded-pkgd.js') }}"></script>
<script src="{{ asset('assets/js/vendor/waypoints.min.js') }}"></script>
<script src="{{ asset('assets/js/vendor/venobox.min.js') }}"></script>
<script src="{{ asset('assets/js/vendor/odometer.min.js') }}"></script>
<script src="{{ asset('assets/js/vendor/meanmenu.js') }}"></script>
<script src="{{ asset('assets/js/vendor/jquery.isotope.js') }}"></script>
<script src="{{ asset('assets/js/vendor/swiper.min.js') }}"></script>
<script src="{{ asset('assets/js/vendor/split-type.min.js') }}"></script>
<script src="{{ asset('assets/js/vendor/gsap.min.js') }}"></script>
<script src="{{ asset('assets/js/vendor/scroll-trigger.min.js') }}"></script>
<script src="{{ asset('assets/js/vendor/scroll-smoother.js') }}"></script>
<script src="{{ asset('assets/js/vendor/jquery.carouselTicker.js') }}"></script>
<script src="{{ asset('assets/js/vendor/nice-select.js') }}"></script>
<script src="{{ asset('assets/js/vendor/three.min.js') }}"></script>
<script src="{{ asset('assets/js/vendor/panolens.min.js') }}"></script>
<script src="{{ asset('assets/js/vendor/jquery.event.move.min.js') }}"></script>
<script src="{{ asset('assets/js/vendor/jquery.twentytwenty.min.js') }}"></script>
<script src="{{ asset('assets/js/slider.js') }}"></script>
<script src="{{ asset('assets/js/banner-process.js') }}"></script>
<script src="{{ asset('assets/js/contact.js') }}"></script>
<script src="{{ asset('assets/js/main.js') }}"></script>
@stack('scripts')
